### ISSUE TITLE
when colabfold_db is initialized no params directory is created 

### ISSUE THREAD

**Issue by rjpbonnal** [nf-core/proteinfold#49]
### Description of the bug

running the pipeline without specifying a `--colabfold_db` starts the creation of the colab database, which downloads the data with aria2c and the performs the untar and later the indexing.
In the specific case of the `alphafold_params` db it download the files, untar and publish them into the `--output` directory `DBs/colabfold_local/`
When the user, later, wants to use the data must specify the `--colabfold_db` with`DBs/colabfold_local/`. The [prepare_colab_fold](https://github.com/nf-core/proteinfold/blob/dev/subworkflows/local/prepare_colabfold_dbs.nf#L35) expects a `DBs/colabfold_local/params/` which does not exists.

the `params` sub-directory is also used by the af2 workflow.

In the mean time, creating a directory and then a symlink to the `alphafold_params_yyyy-mm-dd` dir.

It is also strongly suggested to change the symlink to copy in the [colabfold_local UNTAR process](https://github.com/nf-core/proteinfold/blob/dev/conf/modules.config#L131)

**Comment by athbaltzis** [comment]
I see your point, but if you want to reuse the already downloaded DBs by prepare_colabfold, why not using the `-resume` option of nextflow without providing the `--colabfold_db` path? Regarding the change of the symlink to copy, I agree is super helpful to have all the DB files without a symlink in the specified outdir, but first copying all these files takes a lot of time (especially in the cloud) and, second, it is not storage efficient, since you occupy almost 2 more TBs without any necessity.

**Comment by rjpbonnal** [comment]
`move` is an option.

In the cloud I think that FSx can be an option Francesco Strozzi mentioned that they are using it.

About `-resume`: what if I need to process different data overtime considering the `work` directory persistent/disposable ?

**Comment by athbaltzis** [comment]
Yes, I also think you are right about move + FSx usage. But to me using move instead of symlink doesn't look quite efficient, because you automatically miss the resume option if something goes wrong or you want to rerun something.

You could add multiple entries to your input csv to bypass this issue of course if you know it a priori. Otherwise you have to wait until the execution completes and re-launch the pipeline with the new data.

Since I think what we are discussing really depends on the user "strategy", could you post it to the slack channel so as to see the opinion of the other users and decide how to proceed?

**Comment by athbaltzis** [comment]
Thinking a bit more about your issue, we cannot use `move` with the already existing pipeline structure, because nextflow won't be able to run the downstream processes. What we could do is to add an extra parameter in order to terminate or not the pipeline in the prepare_af2_dbs or prepare_colabfold_dbs subworkflows. This way we can use `move` in the publishDir mode and you can get the DBs and params and rerun the pipeline as many times as you want using the `--af2_db` or `--colabfold_db` params. How does this sound?

**Comment by JoseEspinosa** [comment]
> Thinking a bit more about your issue, we cannot use `move` with the already existing pipeline structure, because nextflow won't be able to run the downstream processes. What we could do is to add an extra parameter in order to terminate or not the pipeline in the prepare_af2_dbs or prepare_colabfold_dbs subworkflows. This way we can use `move` in the publishDir mode and you can get the DBs and params and rerun the pipeline as many times as you want using the `--af2_db` or `--colabfold_db` params. How does this sound?

I think that this won't still solve the problem of having the data with the correct structure and copied instead of symlinked. A possible solution I could think of would be to create a parameter to control whether the user wants to store the data to use it in future runs warning about the problems regarding time and storage efficiency, something as `--copy_dbs`. When set to true then the files should be copied using the convenient folder structure.
